[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.1"
egui = "0.27.1"
image = "0.24.9"
nfd = "0.0.4"

[profile.release]
opt-level = 'z'